name: Python application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Faz o checkout do seu código no runner do GitHub Actions

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        # Configura a versão do Python que você quer usar no seu workflow

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Instala as dependências do seu projeto (incluindo pytest)

    - name: Run tests
      run: |
        pytest
        # Executa os testes do seu projeto com pytest

